# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box     = "trusty32"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty32/version/1/provider/virtualbox.box"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "2.2.2.2"

  config.vm.synced_folder "../www", "/var/www/"

  config.vm.provision "shell", path: "bootstrap.sh"

end
