# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = 'precise32'

	config.vm.network 'forwarded_port', guest: 80, host: 8080
	config.vm.network 'private_network', ip: '2.2.2.2'

	config.vm.synced_folder '../src', '/var/src/'

	config.vm.provision 'ansible' do |ansible|
		ansible.playbook = 'provisioning/playbook.yml'
	end

end
